package data;

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table (name = "Cafeteria")
public class Cafeteria {
	
	/**
	 * The id of the order (auto generated by db)
	 */
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column( name = "Id", nullable=false)
	private int id;
	
	@Column( name = "Cafeteria_Name", nullable=false)
	private String cafeteriaName;
	
	@Column( name = "Server_Ip", nullable=false)
	private String serverIp;
	
	@Column( name = "Admin_Email", nullable=false)
	private String adminEmail;
	
	@Column( name = "Admin_Password", nullable=false)
	private String adminPassword;
	
	@Column( name = "Opening_Hours_Start", nullable=false)
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar openingHoursStart;
	
	@Column( name = "Opening_Hours_End", nullable=false)
	@Temporal(TemporalType.TIMESTAMP)
	private Calendar openingHoursEnd;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCafeteriaName() {
		return cafeteriaName;
	}

	public void setCafeteriaName(String cafeteriaName) {
		this.cafeteriaName = cafeteriaName;
	}

	public String getServerIp() {
		return serverIp;
	}

	public void setServerIp(String serverIp) {
		this.serverIp = serverIp;
	}

	public String getAdminEmail() {
		return adminEmail;
	}

	public void setAdminEmail(String adminEmail) {
		this.adminEmail = adminEmail;
	}

	public String getAdminPassword() {
		return adminPassword;
	}

	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	public Calendar getOpeningHoursStart() {
		return openingHoursStart;
	}

	public void setOpeningHoursStart(Calendar openingHoursStart) {
		this.openingHoursStart = openingHoursStart;
	}

	public Calendar getOpeningHoursEnd() {
		return openingHoursEnd;
	}

	public void setOpeningHoursEnd(Calendar openingHoursEnd) {
		this.openingHoursEnd = openingHoursEnd;
	}

	@Override
	public String toString() {
		return "Cafeteria [id=" + id + ", cafeteriaName=" + cafeteriaName + ", serverIp=" + serverIp + ", adminEmail="
				+ adminEmail + ", adminPassword=" + adminPassword + ", openingHoursStart=" + openingHoursStart
				+ ", openingHoursEnd=" + openingHoursEnd + "]";
	}

	
	
}
