package data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
 * @author Shira Elitzur
 * 
 * An instance of this class represent A single item from the cafeteria menu
 *
 */
@Entity
@Table (name = "items")
public class Item implements Inventory{
	
	/**
	 * The id of this item (auto generated by db)
	 */
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column( name = "Id", nullable=false)
	private int id;
	
	/**
	 * The title of this item.
	 * 1-3 words that describes the item
	 */
	@Column( name = "Title", nullable=false, length=30)
	private String title;
	
	
	/**
	 * The price of this item 
	 */
	@Column( name = "Price", nullable=false)
	private double price;
	
	@Column(name = "In_Stock", nullable=false)
	private boolean inStock;
	
	/**
	 * Returns the id of this item
	 * @return the id of this item
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets id for this item
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Returns the title of this item
	 * @return the title of this item
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets title to this item
	 * @param title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Returns the price of this item
	 * @return
	 */
	public double getPrice() {
		return price;
	}

	/**
	 * Sets price for this item
	 * @param price
	 */
	public void setPrice(double price) {
		this.price = price;
	}

	@Override
	public boolean isInStock() {
		return inStock;
	}

	@Override
	public void setInStock(boolean inStock) {
		this.inStock = inStock;
	}


}
