package data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.SerializedName;

/**
 * 
 * @author Shira Elitzur
 * 
 * An instance of this class represents Main item - the main part of a Meal object
 *
 */
@Entity
@Table (name = "mains")
public class Main implements Inventory {

	/**
	 * The id of this main item (auto generated by db)
	 */
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column( name = "Id", nullable=false)
	private int id;
	
	/**
	 * The title of this main item.
	 * 1-3 words that describes the main item
	 */
	@Column( name = "Title", nullable=false, length=30, unique=true)
	private String title;
	
	@Column( name = "In_Stock", nullable=false)
	private boolean inStock = true;
	
	/**
	 * Returns the id of this main item
	 * @return the id of this main item
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets id for this main item
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Returns the title of this main item
	 * @return the title of this main item
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets title to this main item
	 * @param title
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	
	@Override
	public boolean isInStock() {
		return inStock;
	}

	@Override
	public void setInStock(boolean inStock) {
		this.inStock = inStock;
	}
}
