package data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table (name = "serving")
public class ServingForm implements Inventory{

	/**
	 * The id of this drink (auto generated by db)
	 */
	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column( name = "Id", nullable=false)
	private int id;
	
	/**
	 * The title of this drink.
	 * 1-3 words that describes the drink
	 */
	@Column( name = "Title", nullable=false, length=30, unique=true)
	private String title;
	
	@Column( name = "In_Stock", nullable=false)
	private boolean inStock = true;
	
	/**
	 * Returns the id of this drink
	 * @return the id of this drink
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets id for this drink
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Returns the title of this drink
	 * @return the title of this drink
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets title to this drink
	 * @param title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	@Override
	public boolean isInStock() {
		return inStock;
	}

	@Override
	public void setInStock(boolean inStock) {
		this.inStock = inStock;
	}
	
}
